using System.Collections.Generic;

namespace RTLTMPro {
  public class MirroredCharsMaper {
    public static readonly Dictionary<char, char> MirroredCharsMap = new() {
      { '(', ')' },
      { ')', '(' },
      { '[', ']' },
      { ']', '[' },
      { '{', '}' },
      { '}', '{' },
      { '<', '>' },
      { '>', '<' },
      { '«', '»' },
      { '»', '«' },
      { '「', '」' },
      { '」', '「' },
      { '『', '』' },
      { '』', '『' },
      { '〚', '〛' },
      { '〛', '〚' },
      { '‘', '’' },
      { '’', '‘' },
      { '“', '”' },
      { '”', '“' },
      { '⦗', '⦘' },
      { '⦘', '⦗' },
      { '⟨', '⟩' },
      { '⟩', '⟨' },
      { '⦃', '⦄' },
      { '⦄', '⦃' },
      { '⟦', '⟧' },
      { '⟧', '⟦' },
      { '《', '》' },
      { '》', '《' },
      { '❨', '❩' },
      { '❩', '❨' },
      { '⸨', '⸩' },
      { '⸩', '⸨' },
      { '⌈', '⌉' },
      { '⌉', '⌈' },
      { '⌊', '⌋' },
      { '⌋', '⌊' },
      { '｢', '｣' },
      { '｣', '｢' },
      { '❲', '❳' },
      { '❳', '❲' },
      // custom define, user can replace '<' to 0xFFF0, '>' to 0xFFF1 previously
      { (char)0xFFF0, (char)0xFFF1 },
      { (char)0xFFF1, (char)0xFFF0 },
    };
  }
}
